### ISSUE TITLE
preloading

### ISSUE THREAD

**Issue by badpenguin** [saniyusuf/imagenie#1]
Do you have an example how i can preload all the images i have or i will use in the App?
It will be usefull to do this when i sync the app DB

**Comment by saniyusuf** [comment]
Imagenie is not really for preloading all images, its more of a tool for storing images loaded. So any image that you load with the Imageni attr will only ever be loaded from server once and only once.

**Comment by badpenguin** [comment]
That's good. I've images tags ( img src="" ) stored in the HTML body of a JSON that i cache in localforage too :)
I've a list of all those images extracted from the DB in an array.
Is there an API to preload them? 
Or just a normal javascript image preload script will do the trick?

**Comment by badpenguin** [comment]
using this line of code in a public method will work "imagenieLocalForageInstance.getItem(encodeURIComponent(imageSrc))" 
???

**Comment by saniyusuf** [comment]
Im not sure I understand what you are referring to here.

  [image: photo]
_Sani Yusuf_
Founder, Haibrid LTD
  http://github.com/saniyusuf
http://stackoverflow.com/users/1714088/sani-yusuf
http://about.me/saniyusuf
   http://linkedin.com/in/saniyusuf https://twitter.com/saniyusuf
 Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjkzOTI3IiwgImUiOiAiNTczMjU2ODU0ODc2OTc5MiJ9

On 29 June 2015 at 19:22, Antonio Gallo notifications@github.com wrote:

> using this line of code in a public method will work
> "imagenieLocalForageInstance.getItem(encodeURIComponent(imageSrc))"
> ???
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saniyusuf/imagenie/issues/1#issuecomment-116783529.

## 

Kind Regards
  [image: photo]
_Sani Yusuf_
Co-Founder / CTO, Slapic
  http://github.com/saniyusuf
http://stackoverflow.com/users/1714088/sani-yusuf
http://about.me/saniyusuf
  http://linkedin.com/in/saniyusuf https://twitter.com/saniyusuf
 Get a signature like this:
http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9
Click
here!
http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9

**Comment by badpenguin** [comment]
I want to do this in the code: imagenie.preloadImageFromUrl('http://www.domain.com/test.jpg');
when i sync the app and i have the network connection.

So when the user if off-line and i print {{body}} in the template that contains img src="http://www.domain.com/test.jpg" it will work without i previous access the page with the image.

**Comment by saniyusuf** [comment]
Ahh I see, well all you need to do is use the imagenie in this way <img
src="image.jpg" imagenie> . This tag will automatically do that for you as
long as you have referenced your imagenie src and local-forage in your
index. I hope this helps.

  [image: photo]
_Sani Yusuf_
Founder, Haibrid LTD
  http://github.com/saniyusuf
http://stackoverflow.com/users/1714088/sani-yusuf
http://about.me/saniyusuf
   http://linkedin.com/in/saniyusuf https://twitter.com/saniyusuf
 Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjkzOTI3IiwgImUiOiAiNTczMjU2ODU0ODc2OTc5MiJ9

On 29 June 2015 at 19:27, Antonio Gallo notifications@github.com wrote:

> I want to do this in the code: imagenie.preloadImageFromUrl('
> http://www.domain.com/test.jpg');
> when i sync the app and i have the network connection.
> 
> So when the user if off-line and i print {{body}} in the template that
> contains img src="http://www.domain.com/test.jpg" it will work without i
> previous access the page with the image.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saniyusuf/imagenie/issues/1#issuecomment-116785907.

## 

Kind Regards
  [image: photo]
_Sani Yusuf_
Co-Founder / CTO, Slapic
  http://github.com/saniyusuf
http://stackoverflow.com/users/1714088/sani-yusuf
http://about.me/saniyusuf
  http://linkedin.com/in/saniyusuf https://twitter.com/saniyusuf
 Get a signature like this:
http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9
Click
here!
http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9

**Comment by saniyusuf** [comment]
@badpenguin  any progress?

**Comment by badpenguin** [comment]
Nope. I switched to IMGcache.js that has a little API to work without HTML tags / directives.
Unlucky their lib crash on Winphone 8.1+ so i'm thinking to write an alternative myself.
