### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by 0604hx** [saniyusuf/imagenie#3]
Hi, imagenie is a great tool !  But it is not work for me currently.
 I had include libs as below
        <-script src="lib/localforage.min.js"></script>
        <-script src="lib/angular-localForage.min.js"></script>
        <-script src="lib/imagenie.js"></script>

and then I use this:<-img imagenie="http://pic2.52pk.com/files/111217/781866_025812_1.jpg"/>
but it does not work. 

It is my code wrong?  
Thanks.

**Comment by 0604hx** [comment]
Oh no, I make a wrong code! 
It does not work for I include libs after app.js(Mine code)!

**Comment by pradeepch** [comment]
Hey,
Did it work for you, could you give some hint, I'm also stuck with same problem
